services:
  localstack:
    image: localstack/localstack:3.6
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"
volumes:
  localstack-data: