name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LC}/users-api:${{ steps.vars.outputs.TAG }}"
          docker build -t "$IMAGE" -f docker/users-api/Dockerfile .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Push image
        run: docker push ${{ env.IMAGE }}